# Generated by Django 2.0.3 on 2018-03-12 17:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=200)),
                ('train_percent', models.IntegerField(default=60)),
                ('eval_percent', models.IntegerField(default=20)),
                ('test_percent', models.IntegerField(default=20)),
                ('samples_number', models.IntegerField(default=0)),
                ('labels_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(max_length=200)),
                ('datatype', models.CharField(choices=[('CA', 'Category'), ('NU', 'Numeric')], default='NU', max_length=2)),
                ('use_as', models.CharField(choices=[('IN', 'Input'), ('OU', 'Output'), ('IG', 'Ignore')], default='IN', max_length=2)),
                ('samples', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml.Dataset')),
            ],
        ),
    ]
