# Generated by Django 2.0.3 on 2018-03-13 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='nature',
            field=models.CharField(choices=[('PR', 'Prediction'), ('CL', 'Classification')], default='CL', max_length=2),
        ),
        migrations.AlterField(
            model_name='label',
            name='samples',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default={''}, size=None),
        ),
    ]
