# Generated by Django 2.0.3 on 2018-03-16 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_auto_20180313_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='samples',
            new_name='samplesT',
        ),
        migrations.AddField(
            model_name='label',
            name='samplesN',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=0.0, size=None),
        ),
    ]
