# Generated by Django 2.0.3 on 2018-03-16 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_auto_20180316_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='samplesN',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
