# Generated by Django 2.0.3 on 2018-03-16 09:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20180316_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='samplesN',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None),
        ),
    ]
